FROM mcr.microsoft.com/dotnet/aspnet:6.0 AS base
WORKDIR /app
EXPOSE 80
EXPOSE 443

FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build
WORKDIR /src
COPY ["Queue.Listener/Queue.Listener.csproj", "Queue.Listener/"]
COPY ["SharedKernel/SharedKernel.csproj", "SharedKernel/"]
COPY ["Shared/Shared.csproj", "Shared/"]
COPY ["Broker.Contracts/Broker.Contracts.csproj", "Broker.Contracts/"]
RUN dotnet restore "Queue.Listener/Queue.Listener.csproj"
COPY . .
WORKDIR "/src/Queue.Listener"
RUN dotnet build "Queue.Listener.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "Queue.Listener.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "Queue.Listener.dll"]
