FROM mcr.microsoft.com/dotnet/aspnet:6.0 AS base
WORKDIR /app
EXPOSE 80
EXPOSE 443

FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build
WORKDIR /src
COPY ["Forum/Forum.API/Forum.API.csproj", "Forum/Forum.API/"]
COPY ["Forum/Forum.Infrastructure/Forum.Infrastructure.csproj", "Forum/Forum.Infrastructure/"]
COPY ["Forum/Forum.DAL.Implementations/Forum.DAL.Implementations.csproj", "Forum/Forum.DAL.Implementations/"]
COPY ["Shared/Shared.csproj", "Shared/"]
COPY ["SharedKernel/SharedKernel.csproj", "SharedKernel/"]
COPY ["Forum/Forum.Core/Forum.Core.fsproj", "Forum/Forum.Core/"]
COPY ["Forum/Forum.DAL.Abstractions/Forum.DAL.Abstractions.csproj", "Forum/Forum.DAL.Abstractions/"]
COPY ["Broker.Contracts/Broker.Contracts.csproj", "Broker.Contracts/"]
RUN dotnet restore "Forum/Forum.API/Forum.API.csproj"
COPY . .
WORKDIR "/src/Forum/Forum.API"
RUN dotnet build "Forum.API.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "Forum.API.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "Forum.API.dll"]
