FROM mcr.microsoft.com/dotnet/runtime:6.0 AS base
WORKDIR /app

FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build
WORKDIR /src
COPY ["Forum/Forum.Migrator/Forum.Migrator.csproj", "Forum.Migrator/"]
COPY ["Forum/Forum.DAL.Implementations/Forum.DAL.Implementations.csproj", "Forum.DAL.Implementations/"]
COPY ["Shared/Shared.csproj", "Shared/"]
COPY ["SharedKernel/SharedKernel.csproj", "SharedKernel/"]
COPY ["Forum/Forum.Core/Forum.Core.fsproj", "Forum.Core/"]
COPY ["Forum/Forum.DAL.Abstractions/Forum.DAL.Abstractions.csproj", "Forum.DAL.Abstractions/"]
RUN dotnet restore "Forum.Migrator/Forum.Migrator.csproj"
COPY . .
WORKDIR "/src/Forum/Forum.Migrator"
RUN dotnet build "Forum.Migrator.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "Forum.Migrator.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "Forum.Migrator.dll"]
